set number
#set relativenumber

set tabstop=4
set shiftwidth=4
set expandtab
set smartindent

set hlsearch
set incsearch
set ignorecase
set smartcase

set scrolloff=5
set nowrap

syntax on

" Better splits
set splitbelow
set splitright

" Persistent undo
set undofile
set undodir=~/.vim/undo

" Faster redraw
set ttyfast

" Use block cursor in normal mode
let &t_EI = "\e[2 q"

" Use vertical bar cursor in insert mode
let &t_SI = "\e[6 q"

" Optional: underline cursor in replace mode
let &t_SR = "\e[4 q"


