# Easier split navigation
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# Vim-style pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Better colors
set -g default-terminal "screen-256color"

# Mouse support
set -g mouse off

# Larger history
set -g history-limit 100000

set -ga terminal-overrides ",xterm-256color:Tc"
